apiVersion: devtools.khulnasoft.com/v1alpha1
kind: Component
metadata:
  name: internal-opaque
  title: '@internal/opaque'
spec:
  lifecycle: experimental
  type: devtools-common-library
  owner: maintainers
