apiVersion: devtools.khulnasoft.com/v1alpha1
kind: Component
metadata:
  name: devtools-integration
  title: '@devtools/integration'
  description: Helpers for managing integrations towards external systems
spec:
  lifecycle: production
  type: devtools-common-library
  owner: maintainers
