<script setup lang="ts">
import { buildVideoPrompt, generateVideo, videoAspectRatios, videoDurations, videoModels } from './generate-video.service';
import type { VideoScene } from './generate-video.service';
import AiGatewaySettings from '@/components/AiGatewaySettings.vue';
import { hasAiGateway } from '@/composable/aiGatewayKey';
import TextareaCopyable from '@/components/TextareaCopyable.vue';
import { useDownloadFileFromBase64 } from '@/composable/downloadBase64';

const prompt = ref('A cyclist crossing a foggy bridge at sunrise, slow motion');
const model = ref(videoModels[0].value);
const duration = ref<number>(videoDurations[1]);
const aspectRatio = ref<string>(videoAspectRatios[0]);

const isGenerating = ref(false);
const video = ref('');
const scenes = ref<VideoScene[]>([]);
const isFromGateway = ref(false);

const generationSourceLabel = computed(() => {
  if (isFromGateway.value) {
    return 'Generated by the AI Gateway';
  }

  return hasAiGateway.value ? 'Storyboard generated locally, the AI Gateway call failed' : 'Storyboard generated locally, no AI Gateway key configured';
});

const { download } = useDownloadFileFromBase64({ source: video, filename: 'ai-generated-video', extension: 'mp4' });

async function onGenerate() {
  if (prompt.value.trim() === '') {
    return;
  }

  isGenerating.value = true;
  try {
    const generation = await generateVideo({
      prompt: prompt.value,
      model: model.value,
      duration: duration.value,
      aspectRatio: aspectRatio.value,
    });
    video.value = generation.video;
    scenes.value = generation.scenes;
    isFromGateway.value = generation.source === 'gateway';
  }
  finally {
    isGenerating.value = false;
  }
}
</script>

<template>
  <div style="max-width: 800px; margin: 0 auto">
    <AiGatewaySettings />
    <c-card mb-3 title="Prompt">
      <c-input-text
        v-model:value="prompt"
        placeholder="Describe the video you want to generate..."
        multiline
        :rows="3"
        mb-3
      />

      <div flex gap-3>
        <c-select v-model:value="model" :options="videoModels" label="Model" flex-1 />
        <c-select v-model:value="duration" :options="videoDurations.map(value => ({ label: `${value}s`, value }))" label="Duration" flex-1 />
        <c-select v-model:value="aspectRatio" :options="videoAspectRatios" label="Ratio" flex-1 />
      </div>
    </c-card>

    <div mb-3 flex justify-center gap-3>
      <n-spin v-if="isGenerating" size="small" />
      <c-button type="primary" :disabled="isGenerating || prompt.trim() === ''" @click="onGenerate">
        Generate video
      </c-button>
    </div>

    <c-card v-if="video" title="Generated video">
      <video :src="video" controls style="max-width: 100%; border-radius: 4px" mb-2 />
      <div flex justify-center>
        <c-button @click="download()">
          Download video
        </c-button>
      </div>
    </c-card>

    <c-card v-if="scenes.length > 0" title="Storyboard" mb-3>
      <n-list bordered>
        <n-list-item v-for="scene in scenes" :key="scene.index">
          <div text-sm font-bold>
            Scene {{ scene.index }} — {{ scene.startSecond }}s → {{ scene.startSecond + scene.durationSeconds }}s
            ({{ scene.shot }}, {{ scene.cameraMovement }})
          </div>
          <div text-xs opacity-70>
            {{ scene.description }}
          </div>
        </n-list-item>
      </n-list>

      <TextareaCopyable
        :value="buildVideoPrompt({ prompt, duration, aspectRatio })"
        mt-2
      />
    </c-card>

    <div v-if="scenes.length > 0" text-xs opacity-60>
      {{ generationSourceLabel }}
    </div>
  </div>
</template>
