apiVersion: devtools.khulnasoft.com/v1alpha1
kind: Location
metadata:
  name: example-resources
  description: A collection of all Devtools example resources
spec:
  targets:
    - ./resources/artists-db-resource.yaml
