<script setup lang="ts">
import { defaultObjectFields, defaultObjectPrompt, generateObject, objectModels, parseObjectFields } from './generate-object.service';
import AiGatewaySettings from '@/components/AiGatewaySettings.vue';
import { hasAiGateway } from '@/composable/aiGatewayKey';
import TextareaCopyable from '@/components/TextareaCopyable.vue';

const prompt = ref(defaultObjectPrompt);
const model = ref(objectModels[0].value);
const fieldsText = ref(defaultObjectFields.map(field => `${field.name}: ${field.type}`).join(', '));

const isGenerating = ref(false);
const result = ref('');
const isFromGateway = ref(false);

const generationSourceLabel = computed(() => {
  if (isFromGateway.value) {
    return 'Generated by the AI Gateway';
  }

  return hasAiGateway.value
    ? 'Generated locally, the AI Gateway call failed'
    : 'Generated locally, no AI Gateway key configured';
});

async function onGenerate() {
  if (prompt.value.trim() === '') {
    return;
  }

  isGenerating.value = true;
  try {
    const generation = await generateObject({
      prompt: prompt.value,
      model: model.value,
      fields: parseObjectFields(fieldsText.value),
    });
    result.value = JSON.stringify(generation.object, null, 2);
    isFromGateway.value = generation.source === 'gateway';
  }
  finally {
    isGenerating.value = false;
  }
}
</script>

<template>
  <div style="max-width: 800px; margin: 0 auto">
    <AiGatewaySettings />
    <c-card mb-3 title="Prompt">
      <c-input-text
        v-model:value="prompt"
        placeholder="Describe the object you want to generate..."
        multiline
        :rows="3"
        mb-3
      />

      <c-input-text
        v-model:value="fieldsText"
        label="Fields"
        label-position="left"
        label-width="60px"
        placeholder="title: string, score: number"
        mb-3
      />

      <c-select v-model:value="model" :options="objectModels" label="Model" />
    </c-card>

    <div mb-3 flex justify-center gap-3>
      <n-spin v-if="isGenerating" size="small" />
      <c-button type="primary" :disabled="isGenerating || prompt.trim() === ''" @click="onGenerate">
        Generate object
      </c-button>
    </div>

    <c-card v-if="result" title="Generated object">
      <TextareaCopyable :value="result" language="json" mb-2 />
      <div text-xs opacity-60>
        {{ generationSourceLabel }}
      </div>
    </c-card>
  </div>
</template>
