<script setup lang="ts">
import { generateText, textModels, textTones } from './generate-text.service';
import type { TextTone } from './generate-text.service';
import AiGatewaySettings from '@/components/AiGatewaySettings.vue';
import { hasAiGateway } from '@/composable/aiGatewayKey';
import TextareaCopyable from '@/components/TextareaCopyable.vue';
import { capitalize } from '@/utils/ai-gateway';

const toneOptions = textTones.map(tone => ({ label: capitalize(tone), value: tone }));

const prompt = ref('Explain why small pull requests are easier to review');
const model = ref(textModels[0].value);
const tone = ref<TextTone>('neutral');

const isGenerating = ref(false);
const result = ref('');
const isFromGateway = ref(false);

const generationSourceLabel = computed(() => {
  if (isFromGateway.value) {
    return 'Generated by the AI Gateway';
  }

  return hasAiGateway.value
    ? 'Generated locally, the AI Gateway call failed'
    : 'Generated locally, no AI Gateway key configured';
});

async function onGenerate() {
  if (prompt.value.trim() === '') {
    return;
  }

  isGenerating.value = true;
  try {
    const generation = await generateText({ prompt: prompt.value, model: model.value, tone: tone.value });
    result.value = generation.text;
    isFromGateway.value = generation.source === 'gateway';
  }
  finally {
    isGenerating.value = false;
  }
}
</script>

<template>
  <div style="max-width: 800px; margin: 0 auto">
    <AiGatewaySettings />
    <c-card mb-3 title="Prompt">
      <c-input-text
        v-model:value="prompt"
        placeholder="Describe what you want the model to write..."
        multiline
        :rows="5"
        mb-3
      />

      <div flex gap-3>
        <c-select v-model:value="model" :options="textModels" label="Model" flex-1 />
        <c-select v-model:value="tone" :options="toneOptions" label="Tone" flex-1 />
      </div>
    </c-card>

    <div mb-3 flex justify-center gap-3>
      <n-spin v-if="isGenerating" size="small" />
      <c-button type="primary" :disabled="isGenerating || prompt.trim() === ''" @click="onGenerate">
        Generate text
      </c-button>
    </div>

    <c-card v-if="result" title="Generated text">
      <TextareaCopyable :value="result" mb-2 />
      <div text-xs opacity-60>
        {{ generationSourceLabel }}
      </div>
    </c-card>
  </div>
</template>
