<script setup lang="ts">
import { generateImage, imageModels, imageSizes, imageStyles } from './generate-image.service';
import type { ImageStyle } from './generate-image.service';
import AiGatewaySettings from '@/components/AiGatewaySettings.vue';
import { hasAiGateway } from '@/composable/aiGatewayKey';
import { capitalize } from '@/utils/ai-gateway';
import { useDownloadFileFromBase64Refs } from '@/composable/downloadBase64';
import { useCopy } from '@/composable/copy';

const styleOptions = imageStyles.map(style => ({ label: capitalize(style), value: style }));

const prompt = ref('A lighthouse at dusk, stormy sea, dramatic lighting');
const model = ref(imageModels[0].value);
const size = ref<string>(imageSizes[0]);
const style = ref<ImageStyle>('natural');

const isGenerating = ref(false);
const image = ref('');
const isFromGateway = ref(false);

const generationSourceLabel = computed(() => {
  if (isFromGateway.value) {
    return 'Generated by the AI Gateway';
  }

  return hasAiGateway.value
    ? 'Generated locally, the AI Gateway call failed'
    : 'Generated locally, no AI Gateway key configured';
});

const { copy } = useCopy({ source: image, text: 'Image copied to the clipboard' });
const extension = computed(() => {
  const mimeType = image.value.match(/^data:(.*?);/)?.[1];

  return mimeType === 'image/svg+xml' ? 'svg' : 'png';
});
const { download } = useDownloadFileFromBase64Refs({
  source: image,
  filename: computed(() => 'ai-generated-image'),
  extension,
});

async function onGenerate() {
  if (prompt.value.trim() === '') {
    return;
  }

  isGenerating.value = true;
  try {
    const generation = await generateImage({
      prompt: prompt.value,
      model: model.value,
      size: size.value,
      style: style.value,
    });
    image.value = generation.image;
    isFromGateway.value = generation.source === 'gateway';
  }
  finally {
    isGenerating.value = false;
  }
}
</script>

<template>
  <div style="max-width: 800px; margin: 0 auto">
    <AiGatewaySettings />
    <c-card mb-3 title="Prompt">
      <c-input-text
        v-model:value="prompt"
        placeholder="Describe the image you want to generate..."
        multiline
        :rows="3"
        mb-3
      />

      <div flex gap-3>
        <c-select v-model:value="model" :options="imageModels" label="Model" flex-1 />
        <c-select v-model:value="size" :options="imageSizes" label="Size" flex-1 />
        <c-select v-model:value="style" :options="styleOptions" label="Style" flex-1 />
      </div>
    </c-card>

    <div mb-3 flex justify-center gap-3>
      <n-spin v-if="isGenerating" size="small" />
      <c-button type="primary" :disabled="isGenerating || prompt.trim() === ''" @click="onGenerate">
        Generate image
      </c-button>
    </div>

    <c-card v-if="image" title="Generated image">
      <img :src="image" alt="Generated image" style="max-width: 100%; border-radius: 4px" mb-2>
      <div mb-2 flex justify-center gap-3>
        <c-button @click="copy()">
          Copy image
        </c-button>
        <c-button @click="download()">
          Download image
        </c-button>
      </div>
      <div text-xs opacity-60>
        {{ generationSourceLabel }}
      </div>
    </c-card>
  </div>
</template>
