apiVersion: devtools.khulnasoft.com/v1alpha1
kind: Component
metadata:
  name: devtools-core-compat-api
  title: '@devtools/core-compat-api'
spec:
  lifecycle: experimental
  type: devtools-web-library
  owner: maintainers
