apiVersion: devtools.khulnasoft.com/v1alpha1
kind: Component
metadata:
  name: devtools-frontend-defaults
  title: '@devtools/frontend-defaults'
spec:
  lifecycle: experimental
  type: devtools-web-library
  owner: maintainers
